# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/evaluating-agi',
                'doc_host': 'https://kafkasl.github.io',
                'git_url': 'https://github.com/kafkasl/evaluating-agi',
                'lib_path': 'evaluating_agi'},
  'syms': {}}
